import type { Metadata } from "next";
import "./globals.css";
import { poppins } from "@/utils/font";
import { Toaster } from "react-hot-toast";
import { SessionProvider } from "next-auth/react"


export const metadata: Metadata = {
  title: "Oracle Red Bull Racing",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        className={`${poppins.variable} antialiased`}
      >
        < SessionProvider>{children}</SessionProvider>
        <Toaster position="top-right" reverseOrder={false} />
      </body>
    </html>
  );
}
